# -*- coding: utf-8 -*-
"""cfd_a1_q4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZDmXvBpnH12--a_cPoioW4aZOCL_kmo
"""

In [1]: import pandas as pd

In [2]: import matplotlib.pyplot as plt

nodes=[]
Temperature=[]

with open('fdmq4sol.txt', 'r') as f:
    for line in f:
        row = line.strip().split(':')
        if len(row) == 2:
            try:
                nodes.append(int(row[0]))
                Temperature.append(float(row[1]))
            except ValueError:
                print(f"Error converting line to numbers: {line}")
        else:
            print(f"Invalid line format: {line}")

# Initialize lists for the second file
nodes2 = []
Temperature2 = []

# Read data from the second file
with open('fdmq4analyticalsol.txt', 'r') as f:
    for line in f:
        row = line.strip().split(':')
        if len(row) == 2:
            try:
                nodes2.append(int(row[0]))
                Temperature2.append(float(row[1]))
            except ValueError:
                print(f"Error converting line to numbers in fdmq2analyticalsol.txt: {line}")
        else:
            print(f"Invalid line format in fdmq2analyticalsol.txt: {line}")

if nodes and Temperature:
    # Create the plot
    plt.figure(figsize=(10, 6))  # Optional: adjust figure size
    plt.plot(nodes, Temperature, marker='o', linestyle='-', color='b', label='Temperature vs Nodes')
    plt.plot(nodes2, Temperature2, marker='s', linestyle=':', color='b', label='Temperature vs Nodes(analytical)')

    # Add labels and title
    plt.xlabel('Nodes', fontsize=12)
    plt.ylabel('Temperature (°C)', fontsize=12)
    plt.title('Temperature vs Nodes', fontsize=16)
    plt.grid(True)
    plt.legend()

    # Show the plot
    plt.show()
else:
    print("No data to plot.")